import type { NextPage } from 'next'
import Head from 'next/head'
import { MergeGrid } from '../components/index' 
import { StyledEngineProvider } from '@mui/material/styles'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <StyledEngineProvider injectFirst>
          <MergeGrid />
        </StyledEngineProvider>
      </main>
    </div>
  )
}

export default Home
